bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 A 0
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 A 1
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 A 2
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 A 3
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 A 4
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 B 0
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 B 1
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 B 2
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 B 3
bash wgsim.sh /home/anand/Projects/assembly/data/simulations/sim.chr20 B 4
